services:
  - type: web
    name: india-mf-api
    runtime: node
    plan: starter
    region: oregon
    autoDeploy: true
    buildCommand: |
      cd my-turborepo
      npm install
      npm run build --workspace=apps/api
    startCommand: |
      cd my-turborepo/apps/api
      npm start
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
      - key: DATABASE_URL
        value: "postgresql://ianpinto_admin:Y02GfxJ3pf7JmMW3G0zBmVsMVn8t0kJy@dpg-d4hcdr7diees73bf2qmg-a.oregon-postgres.render.com/imfd_pg_db"
      - key: PORT
        value: "10000"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://india-mf-data-pwa.vercel.app,https://*.vercel.app"
